<?php

namespace DonationBundle\Repository;

/**
 * AssociationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandlineRepository extends \Doctrine\ORM\EntityRepository
{
}